name: 'PullPrompt'
description: 'Comments on pr using a user-defined prompt, generating responses via the Google Gemini API'
author: "Pradumna Saraf"

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  gemini-api-key:
    description: 'API key for the Google Gemini API'
    required: true
  user-prompt:
    description: 'A user-defined prompt for the comment'
    required: false
    default: 'Share an open-source tip in 2 to 3 lines to help developers improve their workflow'
  gemini-model:
    description: 'Model to use for the response. The default is gemini-1.5-flash'
    required: false
    default: "gemini-1.5-flash"
  character-limit:
    description: 'Character limit for the response'
    required: false
    default: "300"
  output-language:
    description: 'Output language for the response'
    required: false
    default: "english"

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: message-circle
  color: 'green'
