name: Run action locally

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prompt: "Tell me about America"
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
